FROM ubuntu:20.04

RUN apt update \
    && apt install -y software-properties-common \ 
    && apt-get update \ 
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt install -y python3.7

RUN apt-get update\
    && apt-get install -y python3-pip \ 
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1 \
    && pip3 install virtualenv \ 
    && python3.7 -m virtualenv nsfw

COPY . nsfw-classifier/

RUN /bin/bash -c "source nsfw/bin/activate \
    && cd nsfw-classifier \ 
    && pip install -r requirements.txt"




