version: '3'

services: 
  backend: 
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports: 
      - "8000:8000"
    volumes: 
      - "/home/laxman/Documents/GitHub/nsfw-classifier:/nsfw-classifier"
  frontend: 
    build: 
      context: .
      dockerfile: src/frontend/Dockerfile
    depends_on: 
      - backend
    ports: 
      - "8501:8501"
    volumes: 
      - "/home/laxman/Documents/GitHub/nsfw-classifier:/nsfw-classifier"